#version: '3.4'

services:

  catalogdb:
    container_name: catalogdb
    image: postgres:15
    environment:

      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/

  basketdb:
    container_name: basketdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data/
  distribuitedcache:
    container_name: distribuitedcache
    restart: always
    ports:
      - "6379:6379"

  catalog.api:
    container_name: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CatalogDb=Host=catalogdb;Port=5432;Database=CatalogDb;Username=postgres;Password=postgres
    ports:
      - "8080:8080"
    depends_on:
      - catalogdb

  basket.api:
    container_name: basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Host=basketdb;Port=5432;Database=BasketDb;Username=postgres;Password=postgres
    ports:
      - "8082:8080"
    depends_on:
      - basketdb